const responseCode = {
    DATA_RECEIVED: 'DATA_RECEIVED',
    SUCCESSFULLY_CREATED: 'SUCCESSFULLY_CREATED',
    FAILED_CREATED: 'FAILED_CREATED',
    SUCCESSFULLY_UPDATED: 'SUCCESSFULLY_UPDATED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    EXCEPTION_OCCURRED: 'EXCEPTION_OCCURRED',
};

const storingType = {
    CURD_FORM : 'CURD_FORM',
    DATA_TABLE : 'DATA_TABLE',
}

export {
    responseCode,
    storingType
}